### ISSUE TITLE
[Suggestion] Consider running phpcs on invoicePDF.php

### ISSUE THREAD

**Issue by vedanshujain** [wceu/camptix-invoices#26] opened 2019-02-19 17:38 UTC
Not a big deal, but this specifically seems to have a lot of code standard violations. It could be because of the nature of the code in that file, but running PHP code standard check and fixing atleast the low hanging fruits should be worth it :) .

**Comment by iandunn** [comment] 2019-02-19 18:01
This looks like a duplicate of #5 ?

**Comment by iceablemedia** [comment] 2019-03-02 14:31
#20 should also make this irrelevant. This file generates invoices with the fpdf library, so it will go away and be replaced as we switch to another pdf library.

**Comment by avillegasn** [comment] 2019-03-04 16:07
383160487434fdeda17f461230a8f66b9dbe6a0a removes all fpdf files.

**Closed as completed by avillegasn** 2019-03-04 16:07 UTC
